# Generated by Django 4.0.1 on 2022-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_remove_user_phone_number_user_login_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
